id: P009182
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG6155
  title: ཞིང་པའི་གཏུག་བཤེར་རྒྱག་ཐབས།
  author: ''
  volumes:
    ef9f2fecd55849d29dea55098108e1ac:
      image_group_id: I1KG8423
      title: ''
      volume_number: 1
      total_pages: 342
