id: I75A2B406
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T17:40:43+00:00'
last_modified: '2022-06-08T09:12:08.842918+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG6155
  title: ཞིང་པའི་གཏུག་བཤེར་རྒྱག་ཐབས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
  base:
    C77B:
      image_group_id: I1KG8423
      title: ''
      total_pages: 342
      order: 1
      base_file: C77B.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
